<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChambreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('chambres')->insert([
            [
                'type_c' => "single",
                'review_c' => "4",
                'capacity_c' => "1 adulte",
                'titre_c' => "Chambre individuelle",
                'prix_c' => "500 DH",
                'image_c' => "chambre/chambre1.jpeg",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "double",
                'review_c' => "4",
                'capacity_c' => "2 adultes",
                'titre_c' => "Chambre double",
                'prix_c' => "800 DH",
                'image_c' => "chambre/chambre2.jpeg",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "suite",
                'review_c' => "4",
                'capacity_c' => "2 adultes + 1 enfant",
                'titre_c' => "Suite familiale",
                'prix_c' => "1200 DH",
                'image_c' => "chambre/chambre3.jpeg",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "classic",
                'review_c' => "4",
                'capacity_c' => "2 adultes",
                'titre_c' => "Chambre classique",
                'prix_c' => "700 DH",
                'image_c' => "chambre/chambre4.jpeg",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "double",
                'review_c' => "4",
                'capacity_c' => "2 adultes",
                'titre_c' => "Chambre double de luxe",
                'prix_c' => "900 DH",
                'image_c' => "chambre/chambre5.jpeg",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "suite",
                'review_c' => "4",
                'capacity_c' => "2 adultes + 2 enfants",
                'titre_c' => "Suite familiale de luxe",
                'prix_c' => "1400 DH",
                'image_c' => "chambre/chambre6.jpeg",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "single",
                'review_c' => "4",
                'capacity_c' => "1 adulte",
                'titre_c' => "Chambre simple",
                'prix_c' => "550 DH",
                'image_c' => "chambre/chambre7.jpeg",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "double",
                'review_c' => "4",
                'capacity_c' => "2 adultes",
                'titre_c' => "Chambre double standard",
                'prix_c' => "750 DH",
                'image_c' => "chambre/chambre8.jpeg",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "suite",
                'review_c' => "5",
                'capacity_c' => "2 adultes + 1 enfant",
                'titre_c' => "Suite de luxe",
                'prix_c' => "1300 DH",
                'image_c' => "chambre/chambre9.jpeg",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "classic",
                'review_c' => "4",
                'capacity_c' => "2 adultes",
                'titre_c' => "Chambre standard",
                'prix_c' => "700 DH",
                'image_c' => "chambre/chambre10.jpeg",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "single",
                'review_c' => "4",
                'capacity_c' => "1 adulte",
                'titre_c' => "Chambre économique",
                'prix_c' => "450 DH",
                'image_c' => "chambre/chambre11.jpg",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "double",
                'review_c' => "4",
                'capacity_c' => "2 adultes",
                'titre_c' => "Chambre de couple",
                'prix_c' => "780 DH",
                'image_c' => "chambre/chambre12.jpg",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "suite",
                'review_c' => "4",
                'capacity_c' => "2 adultes + 2 enfants",
                'titre_c' => "Suite familiale standard",
                'prix_c' => "1250 DH",
                'image_c' => "chambre/chambre13.png",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "classic",
                'review_c' => "4",
                'capacity_c' => "2 adultes",
                'titre_c' => "Chambre avec vue",
                'prix_c' => "720 DH",
                'image_c' => "chambre/chambre14.png",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "single",
                'review_c' => "5",
                'capacity_c' => "1 adulte",
                'titre_c' => "Chambre pour voyageurs solitaires",
                'prix_c' => "480 DH",
                'image_c' => "chambre/chambre15.jpg",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "double",
                'review_c' => "4",
                'capacity_c' => "2 adultes",
                'titre_c' => "Chambre romantique",
                'prix_c' => "820 DH",
                'image_c' => "chambre/chambre16.png",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "suite",
                'review_c' => "4",
                'capacity_c' => "2 adultes + 1 enfant",
                'titre_c' => "Suite nuptiale",
                'prix_c' => "1350 DH",
                'image_c' => "chambre/chambre17.png",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "classic",
                'review_c' => "4",
                'capacity_c' => "2 adultes",
                'titre_c' => "Chambre avec balcon",
                'prix_c' => "730 DH",
                'image_c' => "chambre/chambre18.jpg",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "single",
                'review_c' => "4",
                'capacity_c' => "1 adulte",
                'titre_c' => "Chambre standard pour voyageurs",
                'prix_c' => "510 DH",
                'image_c' => "chambre/chambre19.png",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "double",
                'review_c' => "4",
                'capacity_c' => "2 adultes",
                'titre_c' => "Chambre de luxe",
                'prix_c' => "850 DH",
                'image_c' => "chambre/chambre20.png",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "suite",
                'review_c' => "5",
                'capacity_c' => "2 adultes + 1 enfant",
                'titre_c' => "Suite de luxe avec terrasse",
                'prix_c' => "1450 DH",
                'image_c' => "chambre/chambre21.png",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "classic",
                'review_c' => "4",
                'capacity_c' => "2 adultes",
                'titre_c' => "Chambre confort",
                'prix_c' => "690 DH",
                'image_c' => "chambre/chambre22.png",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "single",
                'review_c' => "4",
                'capacity_c' => "1 adulte",
                'titre_c' => "Chambre économique",
                'prix_c' => "460 DH",
                'image_c' => "chambre/chambre23.png",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "double",
                'review_c' => "4",
                'capacity_c' => "2 adultes",
                'titre_c' => "Chambre d'affaires",
                'prix_c' => "790 DH",
                'image_c' => "chambre/chambre24.png",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "suite",
                'review_c' => "4",
                'capacity_c' => "2 adultes + 1 enfant",
                'titre_c' => "Suite de luxe familiale",
                'prix_c' => "1500 DH",
                'image_c' => "chambre/chambre25.jpg",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "classic",
                'review_c' => "4",
                'capacity_c' => "2 adultes",
                'titre_c' => "Chambre avec kitchenette",
                'prix_c' => "740 DH",
                'image_c' => "chambre/chambre26.jpg",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "single",
                'review_c' => "5",
                'capacity_c' => "1 adulte",
                'titre_c' => "Chambre pour voyageurs en solo",
                'prix_c' => "490 DH",
                'image_c' => "chambre/chambre27.jpg",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "double",
                'review_c' => "4",
                'capacity_c' => "2 adultes",
                'titre_c' => "Chambre romantique de luxe",
                'prix_c' => "830 DH",
                'image_c' => "chambre/chambre28.png",
                'etat_c' => "libre",
            ],
            [
                'type_c' => "suite",
                'review_c' => "4",
                'capacity_c' => "2 adultes + 1 enfant",
                'titre_c' => "Suite nuptiale de luxe",
                'prix_c' => "1550 DH",
                'image_c' => "chambre/chambre29.png",
                'etat_c' => "libre",
            ]
        ]);
    }
}
